language: python

python:
    - "3.6"
    - "3.7-dev"

install: 
    - pip install colorama
    - pip install termcolor
    - pip install print_tree2
    - pip install flask

script:
    - python -m pytest

